name: demeter

services:
  demeter:
    container_name: demeter
    image: athena/demeter:${DEMETER_VERSION:-dev}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - ./src/demeter/config.ini:/root/demeter/src/demeter/config.ini
